apiVersion: v1
kind: Pod
metadata:
  name: test-nginx-pod
  namespace: default
  labels:
    app: test-nginx
    environment: test
    purpose: deletion-test
spec:
  containers:
  - name: nginx
    image: nginx:1.21
    ports:
    - containerPort: 80
      name: http
    resources:
      requests:
        memory: "64Mi"
        cpu: "100m"
      limits:
        memory: "128Mi"
        cpu: "200m"
  restartPolicy: Always
