apiVersion: v1
kind: Service
metadata:
  name: test-nginx-service
  namespace: default
  labels:
    app: test-nginx
    environment: test
spec:
  type: ClusterIP
  selector:
    app: test-nginx
  ports:
  - name: http
    port: 80
    targetPort: 80
    protocol: TCP
